### ISSUE TITLE
Training the Model Resulting Nan for loss as well as dice_coef

### ISSUE THREAD

**Issue by Mahenderreddyp** [as791/Multimodal-Brain-Tumor-Segmentation#1]
I have followed the whole process that is there in main_file.ipynb and preprocessing is also done but while training the model the loss and coeff are coming nan for all the epochs
![image](https://user-images.githubusercontent.com/47118367/150636594-28b24a1c-92d7-46ab-b121-a2b53f27c868.png)

**Comment by as791** [comment]
@Mmsvlife there might be some issue with normalisation please cross check.

**Comment by as791** [comment]
@Mmsvlife please let know if you still facing any issue. Otherwise closing this.
